### ISSUE TITLE
Site isn't being deployed?

### ISSUE THREAD

**Issue by Jarmos-san** [alexdelli/alexpress#10]
First thing, I noticed you configured the [_workflow_ to trigger only on Push events to the `master` branch](https://github.com/alexdelli/alexpress/blob/74f9d2db3ac89e77d557aa930cee978795206c7c/.github/workflows/build.yml#L6). You need to change it to `main` instead. You also need to configure the [`nwtgck/actions-netlify`](https://github.com/nwtgck/actions-netlify) a bit further in case more issues doesn't pop-up. So, ensure [`production-branch` is set to `main`](https://github.com/Jarmos-san/blog/blob/88762e9ed42ef77fbea9004ed9ae980cb92796d9/.github/workflows/build.yml#L27) as well.

**Comment by alexdelli** [comment]
Woooo I don't know I set the branch on Master and not Main...... Now it work, but I think I have to fix the Netlify Token

![image](https://user-images.githubusercontent.com/6674409/132685985-5af92d0d-c1cc-4fa9-bcf2-4b8b5d70b30a.png)

**Comment by alexdelli** [comment]
Last question , I have to swith off the netlify builing, correct?

**Comment by Jarmos-san** [comment]
> Last question , I have to swith off the netlify builing, correct?

Yes, you'll need to disable the build on Netlify. It's an optional process though but I suggest doing it because there's no point of unnecessarily stressing their servers. You can find the option to disable in Netlify under "_Build Options_". See screenshot below for clarification.

![image](https://user-images.githubusercontent.com/31373860/132689601-9e80bbd6-4e9e-467b-a5aa-f68ba0c2b19b.png)

Open new threads & tag me in those if you stumble across issues again.

**Comment by alexdelli** [comment]
thank you again. Finally I have time to write on my blog as wordpress!!!!

**Comment by Jarmos-san** [comment]
> thank you again. Finally I have time to write on my blog as wordpress!!!!

Cheers! I'm glad my work was helpful to someone. Enjoy your blogging journey now.
